trigger:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: Docker@2
  displayName: 'Build & push image to ACR'
  inputs:
    command: buildAndPush
    repository: '$(imageRepository)'
    dockerfile: '$(dockerfilePath)'
    containerRegistry: '$(dockerRegistryServiceConnection)'
    tags: |
      $(imageTag)
    buildContext: '$(buildContext)'

- script: |
    echo "Pushed image: <your-acr-name>.azurecr.io/$(imageRepository):$(imageTag)"
  displayName: 'Show full image name'  branches:
    include: [ main ]

variables:
  dockerRegistryServiceConnection: 'sc-acr'
  imageRepository: 'aks-contoso-app'            # image name inside ACR
  imageTag: '$(Build.BuildId)'
  dockerfilePath: 'Dockerfile'                  # change if Dockerfile is in a subfolder
  buildContext: '$(Build.SourcesDirectory)'

pool:
